"""Domain contracts for Lag-Aware ModMRMR covariate informativeness triage.

This module defines the frozen Pydantic result models for the v0.4.3 Lag-Aware
ModMRMR sparse covariate-lag selector.

ModMRMR modifies the redundancy part of mRMR-style greedy selection by using
multiplicative maximum-similarity suppression against already-selected features.

All models in this module are frozen (immutable after construction) and use
closed Literal label fields for categorical outputs to support deterministic
serialisation and regression fixture comparison.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

# ---------------------------------------------------------------------------
# Type aliases — closed Literal labels
# ---------------------------------------------------------------------------

KnownFutureProvenance = Literal[
    "calendar",
    "schedule",
    "contractual",
    "forecasted_input",
]
"""Provenance of a known-future covariate.

- ``calendar``: calendar flag or indicator (e.g. day-of-week, holiday).
- ``schedule``: planned production, maintenance, or operational schedule.
- ``contractual``: setpoint or setpoint envelope fixed by contract.
- ``forecasted_input``: value generated by an external forecast at creation time.
"""

LagLegalityLabel = Literal[
    "legal",
    "blocked_lag_too_small",
    "blocked_known_future",
    "legal_known_future",
]
"""Legality classification of a lagged covariate candidate.

- ``legal``: lag >= forecast_horizon + availability_margin.
- ``blocked_lag_too_small``: lag < forecast_horizon + availability_margin.
- ``blocked_known_future``: covariate claims known-future but context is a
  realized future observation.
- ``legal_known_future``: covariate is declared known-future with valid
  provenance and bypass is explicit.
"""

NormalizationStrategy = Literal[
    "rank_percentile",
    "surrogate_effect_clip",
    "nmi_min_entropy",
    "nmi_mean_entropy",
    "none",
]
"""Normalization strategy applied to raw scorer values before selection.

- ``rank_percentile``: rank-percentile normalization within the comparison pool.
- ``surrogate_effect_clip``: converts observed-vs-surrogate effect to [0, 1].
- ``nmi_min_entropy``: MI / min(Hx, Hy) when entropy estimates are available.
- ``nmi_mean_entropy``: 2*MI / (Hx + Hy) when entropy estimates are available.
- ``none``: no normalization; raw scorer value is used as-is.
"""

SignificanceMethod = Literal[
    "none",
    "upper_tail_mi_surrogate",
    "bh_fdr_adjustment",
]
"""Significance method applied to relevance scores.

- ``none``: no significance testing; all candidates enter selection.
- ``upper_tail_mi_surrogate``: upper-tail surrogate MI test with n_surrogates >= 99.
- ``bh_fdr_adjustment``: Benjamini–Hochberg FDR correction across all candidates.
"""

RejectionReason = Literal[
    "below_relevance_floor",
    "zero_final_score",
    "max_features_reached",
    "dominated_by_selected",
]
"""Reason a legal candidate was rejected during greedy selection.

- ``below_relevance_floor``: relevance <= relevance_floor before scoring.
- ``zero_final_score``: final score rounded to zero after penalty application.
- ``max_features_reached``: max_selected_features was reached before this candidate.
- ``dominated_by_selected``: candidate is not selected due to greedy ordering.
"""


# ---------------------------------------------------------------------------
# ScorerDiagnostics
# ---------------------------------------------------------------------------


class ScorerDiagnostics(BaseModel):
    """Diagnostic payload returned by a pairwise scorer for one (x, y) pair.

    Attributes:
        raw_value: Original scorer output before any normalization or clipping.
        normalized_value: Score value used by the selector for relevance or
            similarity; lies in [0, 1] for similarity/redundancy scorers and
            >= 0 for relevance scorers.
        p_value: Unadjusted p-value when significance testing is enabled;
            ``None`` when ``significance_method="none"``.
        adjusted_p_value: Multiple-comparisons-adjusted p-value when
            ``significance_method="bh_fdr_adjustment"``; ``None`` otherwise.
        n_pairs: Number of aligned non-missing sample pairs scored.
        estimator_settings: JSON-serializable estimator settings including kNN,
            surrogate, and kernel parameters where applicable.
        normalization: Normalization strategy name applied to produce
            ``normalized_value``.
        significance_method: Significance testing method used.
        bands: Optional reliability bands, clipping notes, or estimator output
            descriptions associated with this pair.
        warnings: Low-sample, convergence, or estimator-specific warnings.
    """

    model_config = ConfigDict(frozen=True)

    raw_value: float = Field(description="Original scorer output before normalization.")
    normalized_value: float = Field(
        ge=0.0,
        description=(
            "Score used by the selector. For similarity/redundancy scorers this "
            "is clipped to [0, 1]. For relevance scorers this is >= 0."
        ),
    )
    p_value: float | None = Field(
        default=None,
        description="Unadjusted p-value; None when significance_method='none'.",
    )
    adjusted_p_value: float | None = Field(
        default=None,
        description=("BH-adjusted p-value; None unless significance_method='bh_fdr_adjustment'."),
    )
    n_pairs: int = Field(ge=1, description="Number of aligned non-missing sample pairs scored.")
    estimator_settings: dict[str, Any] = Field(
        default_factory=dict,
        description="JSON-serializable estimator settings (kNN, surrogate, kernel params).",
    )
    normalization: NormalizationStrategy = Field(
        description="Normalization strategy applied to produce normalized_value.",
    )
    significance_method: SignificanceMethod = Field(
        description="Significance testing method used for this pair.",
    )
    bands: list[str] = Field(
        default_factory=list,
        description="Reliability bands, clipping notes, or estimator descriptions.",
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Low-sample, convergence, or estimator-specific warnings.",
    )

    @field_validator("normalized_value")
    @classmethod
    def _validate_normalized_value(cls, v: float) -> float:
        """Ensure normalized_value is non-negative."""
        if v < 0.0:
            raise ValueError(f"normalized_value must be >= 0.0, got {v}")
        return v


# ---------------------------------------------------------------------------
# PairwiseScorerSpec
# ---------------------------------------------------------------------------


class PairwiseScorerSpec(BaseModel):
    """Specification describing a pairwise scorer used in a selection run.

    Attributes:
        name: Human-readable scorer name (e.g. ``"catt_knn_mi"``).
        backend: Underlying estimator or library backing this scorer.
        normalization: Normalization strategy applied to raw values.
        significance_method: Significance testing method for relevance scores.
        settings: Additional scorer settings (kNN ``k``, n_surrogates, etc.).
    """

    model_config = ConfigDict(frozen=True)

    name: str = Field(description="Scorer identifier (e.g. 'catt_knn_mi', 'spearman_abs').")
    backend: str = Field(
        description="Underlying estimator or library (e.g. 'ksg', 'sklearn', 'scipy').",
    )
    normalization: NormalizationStrategy = Field(
        description="Normalization strategy applied to raw scorer values.",
    )
    significance_method: SignificanceMethod = Field(
        description="Significance testing applied when scoring relevance.",
    )
    settings: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional scorer settings (n_neighbors, n_surrogates, alpha, etc.).",
    )

    @field_validator("name")
    @classmethod
    def _validate_name(cls, v: str) -> str:
        """Require non-empty scorer name."""
        if not v.strip():
            raise ValueError("PairwiseScorerSpec.name must be non-empty")
        return v

    @field_validator("backend")
    @classmethod
    def _validate_backend(cls, v: str) -> str:
        """Require non-empty backend identifier."""
        if not v.strip():
            raise ValueError("PairwiseScorerSpec.backend must be non-empty")
        return v


# ---------------------------------------------------------------------------
# LagAwareModMRMRConfig
# ---------------------------------------------------------------------------


class LagAwareModMRMRConfig(BaseModel):
    """Configuration for a Lag-Aware ModMRMR covariate-lag selection run.

    Attributes:
        forecast_horizon: Forecast horizon h; the number of steps ahead being
            predicted. Must be >= 1.
        availability_margin: Availability margin m; additional lag buffer
            required beyond the forecast horizon. Must be >= 0. A covariate
            at lag k is legal only when ``k >= forecast_horizon + availability_margin``.
        candidate_lags: Explicit candidate lags to evaluate for each covariate.
            When ``None``, the selector derives lags from ``1`` to ``max_lag``.
        max_lag: Maximum lag horizon when ``candidate_lags`` is ``None``.
            Must be >= 1.
        known_future_covariates: Mapping of covariate names to their
            known-future provenance declaration. Covariates in this mapping
            bypass the ordinary lag-cutoff filter. Only values that are
            genuinely known at forecast creation time are valid; realized
            future observations must not be entered here.
        target_lags: Explicit target-history lags used for the novelty penalty.
            Target-history lags must also satisfy
            ``lag >= forecast_horizon + availability_margin``. When ``None``,
            the target-history novelty penalty is disabled.
        max_selected_features: Maximum number of features to include in the
            selected set across all covariates. Must be >= 1.
        relevance_floor: Minimum normalized relevance below which a candidate
            is rejected before any redundancy penalty. Must be in [0, 1).
        relevance_scorer: Scorer spec for computing relevance of each candidate
            against the target.
        redundancy_scorer: Scorer spec for computing similarity between
            candidates and already-selected features.
        target_history_scorer: Scorer spec for computing similarity between
            candidates and target-history lags. When ``None``, the
            target-history novelty penalty is disabled.
    """

    model_config = ConfigDict(frozen=True)

    forecast_horizon: int = Field(ge=1, description="Forecast horizon h (steps ahead).")
    availability_margin: int = Field(
        default=0,
        ge=0,
        description=(
            "Extra lag buffer beyond the forecast horizon. "
            "Covariate lag k is legal when k >= forecast_horizon + availability_margin."
        ),
    )
    candidate_lags: list[int] | None = Field(
        default=None,
        description=(
            "Explicit candidate lags per covariate. None means use range(1, max_lag + 1)."
        ),
    )
    max_lag: int = Field(
        default=20,
        ge=1,
        description="Maximum lag horizon when candidate_lags is None.",
    )
    known_future_covariates: dict[str, KnownFutureProvenance] = Field(
        default_factory=dict,
        description=(
            "Covariate name → known-future provenance. "
            "Covariates listed here bypass the ordinary lag-cutoff. "
            "Realized future observations must not be entered."
        ),
    )
    target_lags: list[int] | None = Field(
        default=None,
        description=(
            "Target-history lags for the novelty penalty. "
            "Must satisfy lag >= forecast_horizon + availability_margin. "
            "None disables the target-history novelty penalty."
        ),
    )
    max_selected_features: int = Field(
        default=10,
        ge=1,
        description="Maximum number of features to include in the selected set.",
    )
    relevance_floor: float = Field(
        default=0.0,
        ge=0.0,
        lt=1.0,
        description=(
            "Minimum normalized relevance. Candidates at or below this floor are "
            "rejected before any redundancy penalty is applied."
        ),
    )
    relevance_scorer: PairwiseScorerSpec = Field(
        description="Scorer spec for relevance of each candidate against the target.",
    )
    redundancy_scorer: PairwiseScorerSpec = Field(
        description=(
            "Scorer spec for similarity between candidates and already-selected features."
        ),
    )
    target_history_scorer: PairwiseScorerSpec | None = Field(
        default=None,
        description=(
            "Scorer spec for similarity between candidates and target-history lags. "
            "None disables the target-history novelty penalty."
        ),
    )

    @field_validator("candidate_lags")
    @classmethod
    def _validate_candidate_lags(cls, v: list[int] | None) -> list[int] | None:
        """Require all candidate lags to be positive integers when provided."""
        if v is None:
            return None
        if len(v) == 0:
            raise ValueError("candidate_lags must be non-empty when provided")
        if any(lag < 1 for lag in v):
            raise ValueError("All candidate_lags must be >= 1")
        return v

    @field_validator("target_lags")
    @classmethod
    def _validate_target_lags(cls, v: list[int] | None) -> list[int] | None:
        """Require all target-history lags to be positive integers when provided."""
        if v is None:
            return None
        if len(v) == 0:
            raise ValueError("target_lags must be non-empty when provided")
        if any(lag < 1 for lag in v):
            raise ValueError("All target_lags must be >= 1")
        return v

    @model_validator(mode="after")
    def _validate_target_history_consistency(self) -> LagAwareModMRMRConfig:
        """Require target_history_scorer when target_lags is set, and vice-versa."""
        has_lags = self.target_lags is not None
        has_scorer = self.target_history_scorer is not None
        if has_lags and not has_scorer:
            raise ValueError("target_history_scorer must be provided when target_lags is set")
        if has_scorer and not has_lags:
            raise ValueError("target_lags must be provided when target_history_scorer is set")
        return self


# ---------------------------------------------------------------------------
# ForecastSafeLagCandidate
# ---------------------------------------------------------------------------


class ForecastSafeLagCandidate(BaseModel):
    """A single lagged covariate candidate after legality assessment.

    Attributes:
        covariate_name: Name of the covariate series.
        lag: Lag value k (z_{j,k}(t) = x_j(t - k)).
        is_known_future: Whether this covariate was declared as known-future.
        known_future_provenance: Provenance label when is_known_future=True;
            ``None`` for ordinary measured covariates.
        is_legal: Whether this candidate is eligible for scoring.
        legality_reason: Legality classification label.
        feature_name: Derived feature identifier (e.g. ``"x_sensor1_lag3"``).
    """

    model_config = ConfigDict(frozen=True)

    covariate_name: str = Field(description="Name of the covariate series.")
    lag: int = Field(ge=0, description="Lag value k.")
    is_known_future: bool = Field(
        default=False,
        description="Whether this covariate was declared as known-future.",
    )
    known_future_provenance: KnownFutureProvenance | None = Field(
        default=None,
        description="Provenance label when is_known_future=True; None otherwise.",
    )
    is_legal: bool = Field(description="Whether this candidate is eligible for scoring.")
    legality_reason: LagLegalityLabel = Field(
        description="Legality classification label.",
    )
    feature_name: str = Field(
        description="Derived feature identifier (e.g. 'x_sensor1_lag3').",
    )

    @model_validator(mode="after")
    def _validate_known_future_consistency(self) -> ForecastSafeLagCandidate:
        """Require provenance when is_known_future=True and vice-versa."""
        if self.is_known_future and self.known_future_provenance is None:
            raise ValueError("known_future_provenance must be set when is_known_future=True")
        if not self.is_known_future and self.known_future_provenance is not None:
            raise ValueError("known_future_provenance must be None when is_known_future=False")
        return self


# ---------------------------------------------------------------------------
# BlockedLagAwareFeature
# ---------------------------------------------------------------------------


class BlockedLagAwareFeature(BaseModel):
    """A lagged covariate candidate that was blocked before scoring.

    Blocked candidates never enter the scoring matrix. Reasons include the lag
    being below the forecast-safe cutoff or a claim of known-future provenance
    that is inconsistent with the selection context.

    Attributes:
        covariate_name: Name of the covariate series.
        lag: Lag value k.
        is_known_future: Whether this covariate was declared as known-future.
        known_future_provenance: Provenance label when is_known_future=True;
            ``None`` for ordinary measured covariates.
        legality_reason: Legality classification label explaining the block.
        feature_name: Derived feature identifier.
        block_reason: Human-readable explanation of why this candidate was blocked.
    """

    model_config = ConfigDict(frozen=True)

    covariate_name: str = Field(description="Name of the covariate series.")
    lag: int = Field(ge=0, description="Lag value k.")
    is_known_future: bool = Field(
        default=False,
        description="Whether this covariate was declared as known-future.",
    )
    known_future_provenance: KnownFutureProvenance | None = Field(
        default=None,
        description="Provenance label when is_known_future=True; None otherwise.",
    )
    legality_reason: LagLegalityLabel = Field(
        description="Legality classification label explaining the block.",
    )
    feature_name: str = Field(description="Derived feature identifier.")
    block_reason: str = Field(
        description="Human-readable explanation of why this candidate was blocked.",
    )


# ---------------------------------------------------------------------------
# SelectedLagAwareFeature
# ---------------------------------------------------------------------------


class SelectedLagAwareFeature(BaseModel):
    """A lagged covariate candidate that was selected by the greedy selector.

    Attributes:
        covariate_name: Name of the covariate series.
        lag: Lag value k.
        is_known_future: Whether this covariate was declared as known-future.
        known_future_provenance: Provenance label when is_known_future=True;
            ``None`` for ordinary measured covariates.
        legality_reason: Legality classification label (``legal`` or
            ``legal_known_future``).
        feature_name: Derived feature identifier.
        relevance: Normalized relevance score against the target; >= 0.
        max_redundancy: Maximum normalized similarity against already-selected
            features; in [0, 1].
        target_history_redundancy: Maximum normalized similarity against
            target-history lags; in [0, 1]. Zero when target-history novelty
            penalty is disabled.
        final_score: Greedy selection score computed as
            ``relevance * (1 - max_redundancy) * (1 - target_history_redundancy)``;
            clipped at 0.
        selection_rank: 1-based position in the greedy selection order.
        relevance_scorer_name: Name of the scorer used for relevance.
        redundancy_scorer_name: Name of the scorer used for redundancy.
        target_history_scorer_name: Name of the scorer used for target-history
            novelty; ``None`` when the penalty is disabled.
        normalization_strategy: Normalization strategy applied across all
            penalty terms in this run.
        relevance_diagnostics: Full diagnostic payload from the relevance scorer;
            ``None`` when diagnostics were not collected.
        redundancy_diagnostics: Full diagnostic payload from the redundancy
            scorer; ``None`` when the candidate was the first selected (no
            redundancy pair exists) or diagnostics were not collected.
        target_history_diagnostics: Full diagnostic payload from the
            target-history scorer; ``None`` when the penalty is disabled or
            diagnostics were not collected.
    """

    model_config = ConfigDict(frozen=True)

    covariate_name: str = Field(description="Name of the covariate series.")
    lag: int = Field(ge=0, description="Lag value k.")
    is_known_future: bool = Field(
        default=False,
        description="Whether this covariate was declared as known-future.",
    )
    known_future_provenance: KnownFutureProvenance | None = Field(
        default=None,
        description="Provenance label when is_known_future=True; None otherwise.",
    )
    legality_reason: LagLegalityLabel = Field(
        description="Legality classification label (legal or legal_known_future).",
    )
    feature_name: str = Field(description="Derived feature identifier.")
    relevance: float = Field(ge=0.0, description="Normalized relevance score against the target.")
    max_redundancy: float = Field(
        ge=0.0,
        le=1.0,
        description=("Maximum normalized similarity against already-selected features; in [0, 1]."),
    )
    target_history_redundancy: float = Field(
        ge=0.0,
        le=1.0,
        description=(
            "Maximum normalized similarity against target-history lags; in [0, 1]. "
            "Zero when target-history novelty penalty is disabled."
        ),
    )
    final_score: float = Field(
        ge=0.0,
        description=(
            "Greedy selection score: "
            "relevance * (1 - max_redundancy) * (1 - target_history_redundancy)."
        ),
    )
    selection_rank: int = Field(
        ge=1,
        description="1-based position in the greedy selection order.",
    )
    relevance_scorer_name: str = Field(description="Name of the scorer used for relevance.")
    redundancy_scorer_name: str = Field(description="Name of the scorer used for redundancy.")
    target_history_scorer_name: str | None = Field(
        default=None,
        description=(
            "Name of the scorer used for target-history novelty; None when the penalty is disabled."
        ),
    )
    normalization_strategy: NormalizationStrategy = Field(
        description="Normalization strategy applied across all penalty terms.",
    )
    relevance_diagnostics: ScorerDiagnostics | None = Field(
        default=None,
        description="Relevance scorer diagnostic payload; None when not collected.",
    )
    redundancy_diagnostics: ScorerDiagnostics | None = Field(
        default=None,
        description=(
            "Redundancy scorer diagnostic payload; None for the first selected "
            "feature or when not collected."
        ),
    )
    target_history_diagnostics: ScorerDiagnostics | None = Field(
        default=None,
        description=(
            "Target-history scorer diagnostic payload; None when penalty is disabled "
            "or not collected."
        ),
    )

    @model_validator(mode="after")
    def _validate_legality_is_legal(self) -> SelectedLagAwareFeature:
        """Selected features must have a legal legality classification."""
        if self.legality_reason not in ("legal", "legal_known_future"):
            raise ValueError(
                f"SelectedLagAwareFeature.legality_reason must be 'legal' or "
                f"'legal_known_future', got {self.legality_reason!r}"
            )
        return self

    @model_validator(mode="after")
    def _validate_known_future_consistency(self) -> SelectedLagAwareFeature:
        """Require provenance when is_known_future=True and vice-versa."""
        if self.is_known_future and self.known_future_provenance is None:
            raise ValueError("known_future_provenance must be set when is_known_future=True")
        if not self.is_known_future and self.known_future_provenance is not None:
            raise ValueError("known_future_provenance must be None when is_known_future=False")
        return self


# ---------------------------------------------------------------------------
# RejectedLagAwareFeature
# ---------------------------------------------------------------------------


class RejectedLagAwareFeature(BaseModel):
    """A legal lagged covariate candidate that was not selected by the greedy selector.

    Rejected candidates were legal (passed the lag-cutoff filter) but were not
    included in the final selected set due to low relevance, zero final score,
    redundancy with already-selected features, or max_features_reached.

    Attributes:
        covariate_name: Name of the covariate series.
        lag: Lag value k.
        is_known_future: Whether this covariate was declared as known-future.
        known_future_provenance: Provenance label when is_known_future=True;
            ``None`` for ordinary measured covariates.
        legality_reason: Legality classification label.
        feature_name: Derived feature identifier.
        relevance: Normalized relevance score against the target; >= 0.
        max_redundancy: Maximum normalized similarity against already-selected
            features at the point of rejection; in [0, 1].
        target_history_redundancy: Maximum normalized similarity against
            target-history lags at the point of rejection; in [0, 1].
        final_score: Greedy selection score at the point of rejection; >= 0.
        rejection_reason: Reason classification for why this candidate was not
            selected.
        relevance_diagnostics: Full diagnostic payload from the relevance scorer;
            ``None`` when not collected or when rejected before scoring.
    """

    model_config = ConfigDict(frozen=True)

    covariate_name: str = Field(description="Name of the covariate series.")
    lag: int = Field(ge=0, description="Lag value k.")
    is_known_future: bool = Field(
        default=False,
        description="Whether this covariate was declared as known-future.",
    )
    known_future_provenance: KnownFutureProvenance | None = Field(
        default=None,
        description="Provenance label when is_known_future=True; None otherwise.",
    )
    legality_reason: LagLegalityLabel = Field(
        description="Legality classification label.",
    )
    feature_name: str = Field(description="Derived feature identifier.")
    relevance: float = Field(ge=0.0, description="Normalized relevance score against the target.")
    max_redundancy: float = Field(
        ge=0.0,
        le=1.0,
        description="Maximum normalized similarity against already-selected features.",
    )
    target_history_redundancy: float = Field(
        ge=0.0,
        le=1.0,
        description=(
            "Maximum normalized similarity against target-history lags. "
            "Zero when target-history novelty penalty is disabled."
        ),
    )
    final_score: float = Field(
        ge=0.0,
        description="Greedy selection score at the point of rejection.",
    )
    rejection_reason: RejectionReason = Field(
        description="Reason classification for why this candidate was not selected.",
    )
    relevance_diagnostics: ScorerDiagnostics | None = Field(
        default=None,
        description="Relevance scorer diagnostic payload; None when not collected.",
    )

    @model_validator(mode="after")
    def _validate_known_future_consistency(self) -> RejectedLagAwareFeature:
        """Require provenance when is_known_future=True and vice-versa."""
        if self.is_known_future and self.known_future_provenance is None:
            raise ValueError("known_future_provenance must be set when is_known_future=True")
        if not self.is_known_future and self.known_future_provenance is not None:
            raise ValueError("known_future_provenance must be None when is_known_future=False")
        return self


# ---------------------------------------------------------------------------
# LagAwareModMRMRResult
# ---------------------------------------------------------------------------


class LagAwareModMRMRResult(BaseModel):
    """Full result payload from a Lag-Aware ModMRMR covariate-lag selection run.

    This is the top-level result returned by ``run_lag_aware_mod_mrmr()``.

    Attributes:
        config: The configuration used for this selection run.
        selected: Ordered list of selected lagged features; ordered by
            ``selection_rank`` ascending.
        rejected: List of legal candidates that were not selected.
        blocked: List of candidates that were blocked before scoring due to
            forecast-horizon legality failures.
        n_candidates_evaluated: Total number of candidates that entered the
            scorer (legal candidates, excluding blocked ones).
        n_candidates_blocked: Total number of candidates blocked due to
            lag-cutoff violations.
        relevance_scorer_spec: Specification of the scorer used for relevance.
        redundancy_scorer_spec: Specification of the scorer used for redundancy.
        target_history_scorer_spec: Specification of the scorer used for
            target-history novelty; ``None`` when the penalty is disabled.
        notes: Human-readable notes about the selection run (e.g. degenerate
            inputs, parameter overrides, or interpretation caveats).
    """

    model_config = ConfigDict(frozen=True)

    config: LagAwareModMRMRConfig = Field(
        description="Configuration used for this selection run.",
    )
    selected: list[SelectedLagAwareFeature] = Field(
        default_factory=list,
        description="Ordered list of selected features by selection_rank ascending.",
    )
    rejected: list[RejectedLagAwareFeature] = Field(
        default_factory=list,
        description="Legal candidates that were not selected.",
    )
    blocked: list[BlockedLagAwareFeature] = Field(
        default_factory=list,
        description="Candidates blocked due to forecast-horizon legality failures.",
    )
    n_candidates_evaluated: int = Field(
        ge=0,
        description=(
            "Total number of legal candidates that entered the scorer "
            "(excluding blocked candidates)."
        ),
    )
    n_candidates_blocked: int = Field(
        ge=0,
        description="Total number of candidates blocked due to lag-cutoff violations.",
    )
    relevance_scorer_spec: PairwiseScorerSpec = Field(
        description="Scorer specification used for relevance scoring.",
    )
    redundancy_scorer_spec: PairwiseScorerSpec = Field(
        description="Scorer specification used for redundancy scoring.",
    )
    target_history_scorer_spec: PairwiseScorerSpec | None = Field(
        default=None,
        description=(
            "Scorer specification used for target-history novelty; "
            "None when the penalty is disabled."
        ),
    )
    notes: list[str] = Field(
        default_factory=list,
        description="Human-readable notes about the selection run.",
    )

    @model_validator(mode="after")
    def _validate_selected_rank_order(self) -> LagAwareModMRMRResult:
        """Require selected features to be ordered by selection_rank ascending."""
        for i, feature in enumerate(self.selected):
            if feature.selection_rank != i + 1:
                raise ValueError(
                    f"selected[{i}].selection_rank must be {i + 1}, got {feature.selection_rank}"
                )
        return self

    @model_validator(mode="after")
    def _validate_counts_consistent(self) -> LagAwareModMRMRResult:
        """Require n_candidates_evaluated and n_candidates_blocked to be consistent."""
        actual_evaluated = len(self.selected) + len(self.rejected)
        if self.n_candidates_evaluated != actual_evaluated:
            raise ValueError(
                f"n_candidates_evaluated ({self.n_candidates_evaluated}) must equal "
                f"len(selected) + len(rejected) ({actual_evaluated})"
            )
        if self.n_candidates_blocked != len(self.blocked):
            raise ValueError(
                f"n_candidates_blocked ({self.n_candidates_blocked}) must equal "
                f"len(blocked) ({len(self.blocked)})"
            )
        return self

    @model_validator(mode="after")
    def _validate_target_history_scorer_consistency(self) -> LagAwareModMRMRResult:
        """Require target_history_scorer_spec consistency with config."""
        config_has_scorer = self.config.target_history_scorer is not None
        result_has_spec = self.target_history_scorer_spec is not None
        if config_has_scorer != result_has_spec:
            raise ValueError(
                "target_history_scorer_spec must be present if and only if "
                "config.target_history_scorer is set"
            )
        return self
